"""
rag_pipeline.py
----------------
Ties retrieval and generation together: builds the prompt sent to
Gemini and parses the final answer.

Pipeline stages covered by this file:

    Top-K Chunks -> Build Prompt -> Gemini -> Final Answer

Two public functions are exposed:
    - build_prompt(question, retrieved_chunks)
    - generate_answer(question, retrieved_chunks)
"""

from typing import List, Tuple

import google.generativeai as genai
from langchain.schema import Document

from config import (
    GEMINI_API_KEY,
    GEMINI_MODEL_NAME,
    GEMINI_MAX_OUTPUT_TOKENS,
    GEMINI_TEMPERATURE,
    NO_ANSWER_MESSAGE,
)


class RAGPipelineError(Exception):
    """Raised when prompt construction or answer generation fails."""


def build_prompt(
    question: str, retrieved_chunks: List[Tuple[Document, float]]
) -> str:
    """
    Construct the final prompt sent to Gemini, containing ONLY the
    retrieved context and the user's question. This is what makes
    the system "grounded" -- Gemini never uses outside knowledge,
    only what was retrieved from the uploaded PDF(s).

    Args:
        question: The user's natural-language question.
        retrieved_chunks: Top-K (Document, score) tuples returned by
            the vector store's similarity search.

    Returns:
        A single formatted prompt string ready to send to Gemini.
    """
    context_blocks = []
    for i, (chunk, _score) in enumerate(retrieved_chunks, start=1):
        page_number = chunk.metadata.get("page", "unknown")
        source_file = chunk.metadata.get("source_file", "document")
        context_blocks.append(
            f"[Chunk {i} | Source: {source_file} | Page: {page_number}]\n"
            f"{chunk.page_content}"
        )
    context_text = "\n\n".join(context_blocks)

    prompt = (
        "You are a precise assistant that answers questions using ONLY "
        "the context provided below. Do not use any outside knowledge.\n\n"
        f"If the answer cannot be found in the context, respond exactly "
        f"with: \"{NO_ANSWER_MESSAGE}\"\n\n"
        "----- CONTEXT START -----\n"
        f"{context_text}\n"
        "----- CONTEXT END -----\n\n"
        f"Question: {question}\n\n"
        "Answer (based strictly on the context above):"
    )
    return prompt


def generate_answer(
    question: str, retrieved_chunks: List[Tuple[Document, float]]
) -> str:
    """
    Send the constructed prompt to Gemini and return the generated
    answer text.

    Args:
        question: The user's natural-language question.
        retrieved_chunks: Top-K (Document, score) tuples from the
            vector store.

    Returns:
        The final answer string generated by Gemini, strictly
        grounded in the retrieved context.

    Raises:
        RAGPipelineError: If the Gemini API key is missing, the
            network call fails, or Gemini returns an unusable
            response.
    """
    if not GEMINI_API_KEY:
        raise RAGPipelineError(
            "Gemini API key is missing. Set the GEMINI_API_KEY "
            "environment variable before running the app."
        )

    if not retrieved_chunks:
        raise RAGPipelineError("No retrieved chunks were provided to generate an answer.")

    prompt = build_prompt(question, retrieved_chunks)

    try:
        genai.configure(api_key=GEMINI_API_KEY)
        model = genai.GenerativeModel(GEMINI_MODEL_NAME)
        response = model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=GEMINI_TEMPERATURE,
                max_output_tokens=GEMINI_MAX_OUTPUT_TOKENS,
            ),
        )
    except Exception as error:
        raise RAGPipelineError(
            "Failed to generate an answer from Gemini. This may be due to "
            f"an invalid API key, network issues, or a Gemini API error. "
            f"Details: {error}"
        ) from error

    answer_text = getattr(response, "text", None)
    if not answer_text or not answer_text.strip():
        raise RAGPipelineError("Gemini returned an empty response.")

    return answer_text.strip()
